Update to Print Link
alphagov/manuals-frontend pull request #1255
Opened 2022-01-26 10:27 UTC by chris-gds

## What

Swap print link on page to use [Print Link component](https://components.publishing.service.gov.uk/component-guide/print_link) from gem

## Why

Closes #1172 

## Visuals

Before > After

![image](https://user-images.githubusercontent.com/71266765/151146710-5b7c731a-50ea-44e3-98d6-8ad66b9061ad.png)

2022-01-28 12:23 UTC, jon-kirwan requested changes
One tiny comment - it looks like there's no need to provide label text here since the default text is: "Print this page" so probably can call the component with:

```
<%= render "govuk_publishing_components/components/print_link", {
} %>
```

2022-01-31 09:41 UTC, jon-kirwan commented
Thanks Chris, approved 👍 

There is an issue with one of the tests which looks related to the version of `i18n`. That looks like it's been updated on `master` (to i18n (1.9.1)) so can probably be solved with a rebase?

```
Fetching gem metadata from https://rubygems.org/.........
[91mYour bundle is locked to i18n (1.9.0), but that version could not be found in
any of the sources listed in your Gemfile. If you haven't changed sources, that
means the author of i18n (1.9.0) has removed it. You'll need to update your
bundle to a version other than i18n (1.9.0) that hasn't been removed in order to
install.
```

2022-01-31 09:42 UTC, jon-kirwan approved these changes

2022-01-31 13:38 UTC, chris-gds commented
Overlap with https://github.com/alphagov/manuals-frontend/pull/1257

2022-01-31 13:40 UTC, chris-gds commented
Hey @chao-xian do you have auth to merge this? (I've bumped `i18n` as part of this)

2022-01-31 13:43 UTC, chao-xian commented
I'd rather the i18n PR merge first if that's ok? I've approved that one already.

2022-01-31 13:52 UTC, chao-xian commented
@chris-gds #1257 is merged now

2022-02-01 18:09 UTC, chris-gds commented
Do you have auth to merge this one @maxgds?

2022-02-02 08:12 UTC, maxgds commented
> Do you have auth to merge this one @maxgds?

@chris-gds It's got some errors right now blocking merge, I don't know if you might need to rebase and/or drop a commit based on the bundle update having gone in separately, maybe?

2022-02-02 14:21 UTC, chris-gds commented
@maxgds jenkins needed a poke its OK now.

2022-02-02 15:16 UTC, merged